### ISSUE TITLE
answer word label

### ISSUE THREAD

**Issue by ziwei75** [minsangkim142/R-net#11] opened 2017-10-15 04:49 UTC
Hi, I am using your data preprocessing for squad right now. I find that too many answer word labels are [0,0] and sometimes they are incorrect. I am not sure why this is happening. Could you please look at it?

**Comment by minsangkim142** [comment] 2017-10-15 06:02
Thanks for raising an issue. I will take a look

**Comment by ziwei75** [comment] 2017-10-15 20:12
Hi, I manually checked some of your answer labels. It seems like the answer word labels are having troubles when the answers are numbers. 
For example, 
paragraph: As aristocrats for centuries samurai developed their own cultures that influenced Japanese culture as a whole The culture associated with the samurai such as the tea ceremony monochrome ink painting rock gardens and poetry were adopted by warrior patrons throughout the centuries -- These practices were adapted from the Chinese arts Zen monks introduced them to Japan and they were allowed to flourish due to the interest of powerful warrior elites Muso\xcc\x84 Soseki -- was a Zen monk who was advisor to both Emperor Go Daigo and General Ashikaga Takauji -- Muso\xcc\x84 as well as other monks acted as political and cultural diplomat between Japan and China Muso\xcc\x84 was particularly well known for his garden design Another Ashikaga patron of the arts was Yoshimasa His cultural advisor the Zen monk Zeami introduced tea ceremony to him Previously tea had been used primarily for Buddhist monks to stay awake during meditation

question: When was Muso Soseki born?
the answer label is [0,0] and the word id is 223 and is mapped to "as", which seems wrong. Same situation happens for several other labels when the answer is a number. 

Also, I am training your data on my own architecture now. And I can tell you my results to see whether is something wrong with the data preprocessing. But thanks for your efforts!

**Comment by minsangkim142** [comment] 2017-10-15 21:21
Hi Ziwei, thanks for pointing out where the processing has gone wrong! I will work on the fix which hopefully should improve the accuracy. Or even better if you could suggest and put a pull request of the solution for this problem.

One last thing, which version of the process.py are you using? Because the paragraph you uploaded seems to have been stripped away of full stops, commas etc. I fixed this issue a while ago and now is just using a normal [tokenizer](https://github.com/minsangkim142/R-net/blob/d355e33f6133e2366a7a76522825102ce076e170/process.py#L150-L155).

**Comment by ziwei75** [comment] 2017-10-15 22:08
Hi, I think I am using the previous version. It contains these two lines:
splitted_line = re.split(r'[`\--=~!@#$%^&*\"“”()_+ \[\]{};\\:"|<,./<>?]', line.strip())
splitted_line = [sl for sl in splitted_line if sl]
I think it shouldn't be a big deal. I previously did data processing on squad and found CorenNlp or nltk fail to split some words. So I manually splitted all the special characters like what you did here.

Also, I will take a look to see whether I can fix this problem in answer labels!

**Comment by minsangkim142** [comment] 2017-10-17 09:12
Hi Ziwei,

I'm having trouble replicating this issue of [0, 0] in answer label. It seems that the issue is fixed as of the latest commit #10  and I don't observe any more wrongly labelled [0, 0] in digits. If this is still not true for your case please let me know how I can replicate this issue! Thanks :)

**Comment by ziwei75** [comment] 2017-10-17 12:50
Hi, Kim,

You are right. I redid data processing using the latest version and the trouble seems already be fixed. I am not sure whether it's because I used a earlier version, the one without spacy. Sorry for this wrong issue.

**Comment by ziwei75** [comment] 2017-10-17 17:41
Hi, Kim,
In your data_load.py, get_batch method:
indices = input_list[-1]
train_ind = np.arange(indices.shape[0],dtype = np.int32)
np.random.shuffle(train_ind)
Seems like you shuffled the train_index not along with other inputs. I didn't implement my code this way because I shuffled my data during processing, but it looks weird to me to not shuffle the indices along with other inputs. I am not sure but it worths a check!

**Closed** 2017-10-19 05:30 UTC
