### ISSUE TITLE
Weird error message when run `python model.py`.

### ISSUE THREAD

**Issue by yangyuan** [minsangkim142/R-net#15] opened 2017-10-22 07:04 UTC
I tried to run this project in a totally new environment. (Ubuntu 16.04 64 bit, Python 2.7)
I strictly followed the instructions. However, I always end with an error message (see below) when I run `python model.py`.

```
Traceback (most recent call last):
  File "model.py", line 258, in <module>
    main()
  File "model.py", line 231, in main
    sess.run(model.train_op)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(8218) > input.dims(1)
         [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]

Caused by op u'passage_char_encoding/bidirectional_rnn/bw/ReverseSequence', defined at:
  File "model.py", line 258, in <module>
    main()
  File "model.py", line 209, in main
    model = Model(is_training = True); print("Built model")
  File "model.py", line 43, in __init__
    self.encode_ids()
  File "model.py", line 81, in encode_ids
    is_training = self.is_training)
  File "/root/nlp/R-net/layers.py", line 98, in bidirectional_GRU
    dtype=tf.float32)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 396, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 389, in _reverse
    seq_dim=seq_dim, batch_dim=batch_dim)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2355, in reverse_sequence
    name=name)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2633, in reverse_sequence
    batch_dim=batch_dim, name=name)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): seq_lens(8218) > input.dims(1)
         [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]
```

Any idea about this problem?

I'm using the current code without any modification.

This this the pip packages I installed.
nltk==3.2.4
numpy==1.13.1
scikit-learn==0.19.0
scipy==0.19.1
spacy==1.9.0
tensorflow==1.2.0
tensorflow-tensorboard==0.1.8
tqdm==4.15.0

**Comment by minsangkim142** [comment] 2017-10-24 00:15
Hi @yangyuan, I tried to replicate this error from the latest commit 5b15ef7ab08cb6d32e5c7fbfbc14de071d267f41 but I couldn't replicate this error. Please try printing the "inputs" from layers.py line 95 before bidirectional_dynamic_rnn is called and post it here?
`print(inputs)`

**Comment by yangyuan** [comment] 2017-10-24 06:57
Thanks for helping, this is the outputs after adding the print
```
Training...
Loading question data...
Loading passage data...
Preparing data...
Tensor("passage_char_encoding/Reshape:0", shape=(15000, 20, 300), dtype=float32)
Tensor("question_char_encoding/Reshape:0", shape=(1500, 20, 300), dtype=float32)
Tensor("concat:0", shape=(50, 300, 428), dtype=float32)
Tensor("concat_1:0", shape=(50, 30, 428), dtype=float32)
Tensor("passage_encoding/concat:0", shape=(50, 300, 128), dtype=float32)
Tensor("attention_match_rnn/question_passage_matching/question_passage_matching_bidirectional/concat:0", shape=(50, 300, 128), dtype=float32)
Tensor("attention_match_rnn/self_matching/self_matching_bidirectional/concat:0", shape=(50, 300, 128), dtype=float32)
Total number of trainable parameters: 1154624
Built model
Loading question data...
Loading passage data...
Preparing data...
2017-10-24 06:53:22.265799: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 06:53:22.265861: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 06:53:22.265868: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 06:53:22.265874: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 06:53:22.265880: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "model.py", line 258, in <module>
    main()
  File "model.py", line 247, in main
    print("\nDev_loss: {}\nDev_Exact_match: {}\nDev_F1_score: {}".format(dev_loss,EM,F1))
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 296, in stop_on_exception
    yield
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 494, in run
    self.run_loop()
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 994, in run_loop
    self._sv.global_step])
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(2299) > input.dims(1)
         [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]

Caused by op u'passage_char_encoding/bidirectional_rnn/bw/ReverseSequence', defined at:
  File "model.py", line 258, in <module>
    main()
  File "model.py", line 209, in main
    model = Model(is_training = True); print("Built model")
  File "model.py", line 43, in __init__
    self.encode_ids()
  File "model.py", line 81, in encode_ids
    is_training = self.is_training)
  File "/root/nlp/R-net/layers.py", line 98, in bidirectional_GRU
    dtype=tf.float32)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 396, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 389, in _reverse
    seq_dim=seq_dim, batch_dim=batch_dim)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2355, in reverse_sequence
    name=name)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2633, in reverse_sequence
    batch_dim=batch_dim, name=name)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/root/nlp/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): seq_lens(2299) > input.dims(1)
         [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]

```

**Comment by huangpeng1126** [comment] 2017-10-24 08:34
I have the same issue, the following is the output (add print(inputs) statement as suggested above):

Training...
Loading question data...
Loading passage data...
^@Preparing data...
Tensor("passage_embeddings/embedding_lookup_1:0", shape=(50, 300, 20, 300), dtype=float32, device=/device:CPU:0)
Tensor("question_embeddings/embedding_lookup_1:0", shape=(50, 30, 20, 300), dtype=float32, device=/device:CPU:0)
Tensor("concat:0", shape=(50, 300, 428), dtype=float32)
Tensor("concat_1:0", shape=(50, 30, 428), dtype=float32)
Tensor("passage_encoding/concat:0", shape=(50, 300, 128), dtype=float32)
Tensor("attention_match_rnn/question_passage_matching/question_passage_matching_bidirectional/concat:0", shape=(50, 300, 128), dtype=float32)
Tensor("attention_match_rnn/self_matching/self_matching_bidirectional/concat:0", shape=(50, 300, 128), dtype=float32)
Total number of trainable parameters: 1154624
Built model
Loading question data...
Loading passage data...
Preparing data...
^@2017-10-24 16:16:19.845741: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 16:16:19.845769: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 16:16:19.845774: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 16:16:19.845779: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
  0%|                                         | 0/1700 [00:00<?, ?b/s]^@^@Traceback (most recent call last):
  File "model.py", line 279, in <module>
    main()
  File "model.py", line 255, in main
    logits, dev_loss = sess.run([model.points_logits, model.mean_loss], feed_dict=feed_dict)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(7306) > input.dims(1)
	 [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]

Caused by op u'passage_char_encoding/bidirectional_rnn/bw/ReverseSequence', defined at:
  File "model.py", line 279, in <module>
    main()
  File "model.py", line 224, in main
    model = Model(is_training=True);
  File "model.py", line 44, in __init__
    self.encode_ids()
  File "model.py", line 87, in encode_ids
    is_training=self.is_training)
  File "/Users/peng.huangp/github/R-net/layers.py", line 118, in bidirectional_GRU
    dtype=tf.float32)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 426, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 419, in _reverse
    seq_dim=seq_dim, batch_dim=batch_dim)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2394, in reverse_sequence
    name=name)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2801, in reverse_sequence
    batch_dim=batch_dim, name=name)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/peng.huangp/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): seq_lens(7306) > input.dims(1)
	 [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]

**Comment by Levstyle** [comment] 2017-10-24 08:41
I got the same issue  when i ran model.py

```
Traceback (most recent call last):                                    
  File "model.py", line 258, in <module>
    main()
  File "model.py", line 231, in main
    sess.run(model.train_op)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(4212) > input.dims(1)
	 [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]

Caused by op u'passage_char_encoding/bidirectional_rnn/bw/ReverseSequence', defined at:
  File "model.py", line 258, in <module>
    main()
  File "model.py", line 209, in main
    model = Model(is_training = True); print("Built model")
  File "model.py", line 43, in __init__
    self.encode_ids()
  File "model.py", line 81, in encode_ids
    is_training = self.is_training)
  File "/home/lev/Code/R-net/layers.py", line 98, in bidirectional_GRU
    dtype=tf.float32)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 396, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 389, in _reverse
    seq_dim=seq_dim, batch_dim=batch_dim)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2355, in reverse_sequence
    name=name)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2633, in reverse_sequence
    batch_dim=batch_dim, name=name)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/lev/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): seq_lens(4212) > input.dims(1)
	 [[Node: passage_char_encoding/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/cpu:0"](passage_char_encoding/Reshape, passage_char_encoding/Reshape_1)]]

```

**Comment by thisum** [comment] 2017-10-24 14:51
I ran into the same error. Did anyone come up with a solution?

**Comment by Levstyle** [comment] 2017-10-24 15:15
@thisum I have not figured out how the point network works!  So i do not know how to fix it! I need more time to figure out the shape of every tensor!.

**Comment by minsangkim142** [comment] 2017-10-24 20:26
Thanks for the detailed report! I am working on the fix. In the meantime please try previous versions f14e6280564dfc4fa906311cc7c64ac719860257 and let me know if it works, so we can locate down the problem.

**Comment by yangyuan** [comment] 2017-10-25 05:43
@minsangkim142 f14e628 gives similar errors. :(

**Comment by huangpeng1126** [comment] 2017-10-28 11:19
File 'data_load.py' in line 146 & 147 (    p_char_len = pad_data(p_char_len,p_max_word)
    q_char_len = pad_data(q_char_len,q_max_word ), there is a potential bug for word length greater than 20(max_char)

**Comment by minsangkim142** [comment] 2017-10-28 21:25
Hi @huangpeng1126 thanks for suggesting a solution! Do you mean there is a bug in these lines below in process.py file?
https://github.com/minsangkim142/R-net/blob/5b15ef7ab08cb6d32e5c7fbfbc14de071d267f41/process.py#L228-L250
Would you mind putting a pr for the fix?
Thanks :)

**Comment by purnendu91** [comment] 2017-11-03 16:08
@huangpeng1126 Can you provide the fix, please? Thanks! :)

**Comment by huangpeng1126** [comment] 2017-11-04 00:33
@minsangkim142 , I have 2 modification:

1.  define a new function in 'process.py':
```python
def pad_char_len(data, max_word, max_char):
    padded_data = np.zeros((len(data), max_word), dtype=np.int32)
    for i, line in enumerate(data):
        for j, word in enumerate(line):
            if j >= max_word:
                break
            padded_data[i, j] = word if word <= max_char else max_char
    return padded_data
```
2. File 'data_load.py' in line 143~147 change to the following:
```python
# to numpy
    indices = np.reshape(np.asarray(indices, np.int32), (-1, 2))
    p_word_len = np.reshape(np.asarray(p_word_len, np.int32), (-1, 1))
    q_word_len = np.reshape(np.asarray(q_word_len, np.int32), (-1, 1))
    # p_char_len = pad_data(p_char_len, p_max_word)
    # q_char_len = pad_data(q_char_len, q_max_word)
    p_char_len = pad_char_len(p_char_len, p_max_word, p_max_char)
    q_char_len = pad_char_len(q_char_len, q_max_word, q_max_char)
    # fix p(q)_word_len
    for i in range(p_word_len.shape[0]):
        if p_word_len[i,0] > p_max_word:
            p_word_len[i,0] = p_max_word
    for i in range(q_word_len.shape[0]):
        if q_word_len[i,0] > q_max_word:
            q_word_len[i,0] = q_max_word
```

**Comment by Observerspy** [comment] 2017-11-06 08:30
I ran ingot the same error here. Is there any solution? Thx.

**Comment by Observerspy** [comment] 2017-11-07 00:21
@huangpeng1126 ,Thx, it works.

**Comment by minsangkim142** [comment] 2017-11-07 00:32
Committed e70680c4169c6b7fc9c09ac7a3ad05d1194b5656. Thanks alot!

**Closed by minsangkim142** 2017-11-07 00:32 UTC
